name: Build and Test MinIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-minio:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout source code
        uses: actions/checkout@v3
        
      # 2. 确保拉取完整代码子模块
      - name: Ensure submodules are downloaded
        run: git submodule update --init --recursive

      # 3. 设置 MINIO_CI_CD 环境变量
      - name: Setup environment variables
        run: |
          echo "MINIO_CI_CD=1" >> $GITHUB_ENV
          echo "MinIO CI/CD mode enabled"

      # 4. 安装 Go 环境
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # 5. 下载依赖并编译 MinIO
      - name: Build MinIO from source
        run: |
          go mod tidy
          echo "Building MinIO from source..."
          go build -v -o minio
          echo "Build successful."

      # 6. 检查二进制文件生成
      - name: Verify MinIO Executable
        run: |
          ls -l ./minio
          file ./minio
          if [[ -f "./minio" && -x "./minio" ]]; then
            echo "MinIO binary is successfully built and executable."
          else
            echo "ERROR: MinIO binary not found or not executable!"
            exit 1
          fi

      # 7. 运行 MinIO（可选，用于测试）
      - name: Start MinIO for local testing
        env:
          MINIO_ACCESS_KEY: testuser
          MINIO_SECRET_KEY: testpass123
          MINIO_CI_CD: ${{ env.MINIO_CI_CD }}
        run: |
          echo "Starting MinIO server..."
          ./minio server /data --console-address ":9001" &
          sleep 5
          curl --fail http://127.0.0.1:9001 || exit 1
          echo "MinIO server is running successfully."
