name: Build MinIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-minio:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出当前用户的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 拉取 MinIO 项目源码
      - name: Clone MinIO Repository
        run: |
          echo "Cloning MinIO source code..."
          git clone --depth=1 https://github.com/minio/minio.git ./minio
          cd ./minio
          git log -1 --oneline

      # 3. 设置环境变量 MINIO_CI_CD
      - name: Setup Environment Variables
        run: |
          echo "MINIO_CI_CD=1" >> $GITHUB_ENV
          echo "MinIO CI/CD mode enabled."

      # 4. 安装 Go 环境
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      # 5. 下载依赖和构建
      - name: Install dependencies and build MinIO
        working-directory: ./minio
        run: |
          echo "Downloading dependencies..."
          go mod tidy
          echo "Building MinIO binary..."
          go build -v -o ./bin/minio
          echo "MinIO successfully built at ./minio/bin/minio"

      # 6. 测试二进制文件是否构建成功
      - name: Verify MinIO Binary
        run: |
          if [[ -f "./minio/bin/minio" ]]; then
            echo "MinIO binary successfully built!"
          else
            echo "ERROR: MinIO binary not found!"
            exit 1
          fi
