name: Build and Test MinIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-minio:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. 设置环境变量 MINIO_CI_CD
      - name: Setup environment variables
        run: |
          echo "MINIO_CI_CD=1" >> $GITHUB_ENV
          echo "MinIO CI/CD mode enabled"

      # 3. 安装 Go 环境
      - name: Configure Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20' # MinIO 要求 1.19 或更新版本

      # 4. 安装依赖包
      - name: Install build tools and dependencies
        run: |
          go mod tidy
          go mod vendor

      # 5. 下载 MinIO 的源码并编译
      - name: Build MinIO from source
        run: |
          echo "Start building MinIO..."
          go version # 检查 Go 版本
          go build -v -o minio # 将生成的二进制文件命名为 minio
          echo "MinIO binary build completed."

      # 6. 验证二进制文件是否生成
      - name: Verify MinIO Executable
        run: |
          if [[ -f "./minio" && -x "./minio" ]]; then
            echo "MinIO binary is successfully built and executable."
          else
            echo "ERROR: MinIO binary not found or not executable!"
            exit 1
          fi

      # 7. 运行 MinIO for testing（可选）
      - name: Start MinIO for testing
        env:
          MINIO_ACCESS_KEY: testuser
          MINIO_SECRET_KEY: testpass123
          MINIO_CI_CD: ${{ env.MINIO_CI_CD }}
        run: |
          echo "Starting MinIO server..."
          ./minio server /data --console-address ":9001" &
          sleep 5 # 等待 MinIO 启动
          curl --fail http://127.0.0.1:9001 || exit 1
          echo "MinIO server is running successfully."

