name: Build and Test MinIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-minio:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置运行时环境变量
    - name: Setup Environment Variables
      run: |
        echo "MINIO_CI_CD=1" >> $GITHUB_ENV
        echo "MinIO CI/CD MODE Enabled"

    # 安装必要的依赖项 (Go 构建工具)
    - name: Setup Go Environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x

    # 拉取 MinIO 源码并编译
    - name: Build MinIO
      run: |
        # 输出调试日志
        echo "Compiling MinIO from source"
        go version
        
        # 执行构建步骤
        make build
        MINIO_EXECUTABLE=$(find ./ -type f -name "minio" -executable -print -quit)
        
